# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'manual.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(1051, 754)
        MainWindow.setWindowTitle("Rostu Manual Monitor")
        MainWindow.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.manualTab = QtWidgets.QTabWidget(self.centralwidget)
        self.manualTab.setGeometry(QtCore.QRect(10, 10, 1031, 341))
        self.manualTab.setObjectName("manualTab")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.tab)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 451, 105))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label.setIndent(-1)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.speedSlider = QtWidgets.QSlider(self.verticalLayoutWidget)
        self.speedSlider.setMaximum(255)
        self.speedSlider.setTracking(True)
        self.speedSlider.setOrientation(QtCore.Qt.Horizontal)
        self.speedSlider.setObjectName("speedSlider")
        self.verticalLayout.addWidget(self.speedSlider)
        self.speedInput = QtWidgets.QSpinBox(self.verticalLayoutWidget)
        self.speedInput.setMaximum(255)
        self.speedInput.setObjectName("speedInput")
        self.verticalLayout.addWidget(self.speedInput)
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.tab)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 130, 451, 171))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.directionDial = QtWidgets.QDial(self.horizontalLayoutWidget)
        self.directionDial.setMinimum(-270)
        self.directionDial.setMaximum(90)
        self.directionDial.setProperty("value", 90)
        self.directionDial.setSliderPosition(90)
        self.directionDial.setOrientation(QtCore.Qt.Vertical)
        self.directionDial.setInvertedAppearance(True)
        self.directionDial.setInvertedControls(False)
        self.directionDial.setWrapping(True)
        self.directionDial.setNotchTarget(0.0)
        self.directionDial.setObjectName("directionDial")
        self.verticalLayout_2.addWidget(self.directionDial)
        self.directionInput = QtWidgets.QSpinBox(self.horizontalLayoutWidget)
        self.directionInput.setMaximum(360)
        self.directionInput.setObjectName("directionInput")
        self.verticalLayout_2.addWidget(self.directionInput)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_3 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_3.addWidget(self.label_3)
        self.rotationDial = QtWidgets.QDial(self.horizontalLayoutWidget)
        self.rotationDial.setMouseTracking(False)
        self.rotationDial.setTabletTracking(False)
        self.rotationDial.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.rotationDial.setAcceptDrops(False)
        self.rotationDial.setToolTip("")
        self.rotationDial.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.rotationDial.setMinimum(-255)
        self.rotationDial.setMaximum(255)
        self.rotationDial.setPageStep(10)
        self.rotationDial.setProperty("value", 0)
        self.rotationDial.setSliderPosition(0)
        self.rotationDial.setTracking(True)
        self.rotationDial.setOrientation(QtCore.Qt.Horizontal)
        self.rotationDial.setInvertedAppearance(False)
        self.rotationDial.setInvertedControls(False)
        self.rotationDial.setNotchTarget(0.0)
        self.rotationDial.setNotchesVisible(False)
        self.rotationDial.setObjectName("rotationDial")
        self.verticalLayout_3.addWidget(self.rotationDial)
        self.rotationInput = QtWidgets.QSpinBox(self.horizontalLayoutWidget)
        self.rotationInput.setMinimum(-255)
        self.rotationInput.setMaximum(255)
        self.rotationInput.setObjectName("rotationInput")
        self.verticalLayout_3.addWidget(self.rotationInput)
        self.horizontalLayout.addLayout(self.verticalLayout_3)
        self.verticalLayoutWidget_4 = QtWidgets.QWidget(self.tab)
        self.verticalLayoutWidget_4.setGeometry(QtCore.QRect(470, 10, 231, 170))
        self.verticalLayoutWidget_4.setObjectName("verticalLayoutWidget_4")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_4)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_6 = QtWidgets.QLabel(self.verticalLayoutWidget_4)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_6.addWidget(self.label_6)
        self.kickChargeTimeInput = QtWidgets.QSpinBox(self.verticalLayoutWidget_4)
        self.kickChargeTimeInput.setProperty("value", 3)
        self.kickChargeTimeInput.setObjectName("kickChargeTimeInput")
        self.verticalLayout_6.addWidget(self.kickChargeTimeInput)
        self.kickButton = QtWidgets.QPushButton(self.verticalLayoutWidget_4)
        self.kickButton.setObjectName("kickButton")
        self.verticalLayout_6.addWidget(self.kickButton)
        self.kickerStatusLabel = QtWidgets.QLabel(self.verticalLayoutWidget_4)
        self.kickerStatusLabel.setObjectName("kickerStatusLabel")
        self.verticalLayout_6.addWidget(self.kickerStatusLabel)
        self.layoutWidget = QtWidgets.QWidget(self.tab)
        self.layoutWidget.setGeometry(QtCore.QRect(470, 190, 231, 111))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.manualRunToggle = QtWidgets.QCheckBox(self.layoutWidget)
        self.manualRunToggle.setObjectName("manualRunToggle")
        self.verticalLayout_4.addWidget(self.manualRunToggle)
        self.verticalLayoutWidget_6 = QtWidgets.QWidget(self.tab)
        self.verticalLayoutWidget_6.setGeometry(QtCore.QRect(710, 10, 271, 170))
        self.verticalLayoutWidget_6.setObjectName("verticalLayoutWidget_6")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_6)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_12 = QtWidgets.QLabel(self.verticalLayoutWidget_6)
        self.label_12.setObjectName("label_12")
        self.verticalLayout_7.addWidget(self.label_12)
        self.dribbleMenu = QtWidgets.QComboBox(self.verticalLayoutWidget_6)
        self.dribbleMenu.setObjectName("dribbleMenu")
        self.dribbleMenu.addItem("")
        self.dribbleMenu.addItem("")
        self.verticalLayout_7.addWidget(self.dribbleMenu)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_13 = QtWidgets.QLabel(self.verticalLayoutWidget_6)
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_5.addWidget(self.label_13)
        self.dribbleSpeedInput = QtWidgets.QSpinBox(self.verticalLayoutWidget_6)
        self.dribbleSpeedInput.setMaximum(255)
        self.dribbleSpeedInput.setObjectName("dribbleSpeedInput")
        self.horizontalLayout_5.addWidget(self.dribbleSpeedInput)
        self.verticalLayout_7.addLayout(self.horizontalLayout_5)
        self.manualTab.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.layoutWidget_2 = QtWidgets.QWidget(self.tab_2)
        self.layoutWidget_2.setGeometry(QtCore.QRect(10, 10, 201, 121))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.layoutWidget_2)
        self.verticalLayout_14.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.catchBallDribble_4 = QtWidgets.QRadioButton(self.layoutWidget_2)
        self.catchBallDribble_4.setObjectName("catchBallDribble_4")
        self.verticalLayout_14.addWidget(self.catchBallDribble_4)
        self.catchBallDribble_5 = QtWidgets.QRadioButton(self.layoutWidget_2)
        self.catchBallDribble_5.setObjectName("catchBallDribble_5")
        self.verticalLayout_14.addWidget(self.catchBallDribble_5)
        self.manualTab.addTab(self.tab_2, "")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.horizontalLayoutWidget_3 = QtWidgets.QWidget(self.tab_5)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(10, 10, 269, 51))
        self.horizontalLayoutWidget_3.setObjectName("horizontalLayoutWidget_3")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_10 = QtWidgets.QLabel(self.horizontalLayoutWidget_3)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_4.addWidget(self.label_10)
        self.spinBox = QtWidgets.QSpinBox(self.horizontalLayoutWidget_3)
        self.spinBox.setObjectName("spinBox")
        self.horizontalLayout_4.addWidget(self.spinBox)
        self.horizontalLayoutWidget_5 = QtWidgets.QWidget(self.tab_5)
        self.horizontalLayoutWidget_5.setGeometry(QtCore.QRect(10, 70, 269, 51))
        self.horizontalLayoutWidget_5.setObjectName("horizontalLayoutWidget_5")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_5)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_11 = QtWidgets.QLabel(self.horizontalLayoutWidget_5)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_7.addWidget(self.label_11)
        self.spinBox_2 = QtWidgets.QSpinBox(self.horizontalLayoutWidget_5)
        self.spinBox_2.setObjectName("spinBox_2")
        self.horizontalLayout_7.addWidget(self.spinBox_2)
        self.layoutWidget_3 = QtWidgets.QWidget(self.tab_5)
        self.layoutWidget_3.setGeometry(QtCore.QRect(290, 10, 201, 111))
        self.layoutWidget_3.setObjectName("layoutWidget_3")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout(self.layoutWidget_3)
        self.verticalLayout_15.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.catchBallDribble_6 = QtWidgets.QRadioButton(self.layoutWidget_3)
        self.catchBallDribble_6.setObjectName("catchBallDribble_6")
        self.verticalLayout_15.addWidget(self.catchBallDribble_6)
        self.catchBallDribble_7 = QtWidgets.QRadioButton(self.layoutWidget_3)
        self.catchBallDribble_7.setObjectName("catchBallDribble_7")
        self.verticalLayout_15.addWidget(self.catchBallDribble_7)
        self.manualTab.addTab(self.tab_5, "")
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(20, 360, 951, 151))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.robotStatusMonitor = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.robotStatusMonitor.setObjectName("robotStatusMonitor")
        self.horizontalLayout_2.addWidget(self.robotStatusMonitor)
        self.wheelMonitor = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.wheelMonitor.setObjectName("wheelMonitor")
        self.horizontalLayout_2.addWidget(self.wheelMonitor)
        self.dribbleMonitor = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.dribbleMonitor.setSizeIncrement(QtCore.QSize(17, 15))
        self.dribbleMonitor.setLineWidth(1)
        self.dribbleMonitor.setObjectName("dribbleMonitor")
        self.horizontalLayout_2.addWidget(self.dribbleMonitor)
        self.positionMonitor = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.positionMonitor.setObjectName("positionMonitor")
        self.horizontalLayout_2.addWidget(self.positionMonitor)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.manualTab.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        self.label.setText(_translate("MainWindow", "Speed (0 - 255)"))
        self.label_2.setText(_translate("MainWindow", "Direction (0 - 360)"))
        self.label_3.setText(_translate("MainWindow", "Rotation Speed (-255 - 255)"))
        self.label_6.setText(_translate("MainWindow", "Set Charge Time (Second)"))
        self.kickButton.setText(_translate("MainWindow", "Kick"))
        self.kickerStatusLabel.setText(_translate("MainWindow", "Status : stop"))
        self.manualRunToggle.setText(_translate("MainWindow", "Run"))
        self.label_12.setText(_translate("MainWindow", "Dribble"))
        self.dribbleMenu.setItemText(0, _translate("MainWindow", "Stop"))
        self.dribbleMenu.setItemText(1, _translate("MainWindow", " Catch Ball"))
        self.label_13.setText(_translate("MainWindow", "Speed"))
        self.manualTab.setTabText(self.manualTab.indexOf(self.tab), _translate("MainWindow", "Manual"))
        self.catchBallDribble_4.setText(_translate("MainWindow", "Run"))
        self.catchBallDribble_5.setText(_translate("MainWindow", "Stop"))
        self.manualTab.setTabText(self.manualTab.indexOf(self.tab_2), _translate("MainWindow", "Chase ball"))
        self.label_10.setText(_translate("MainWindow", "X"))
        self.label_11.setText(_translate("MainWindow", "Y"))
        self.catchBallDribble_6.setText(_translate("MainWindow", "Run"))
        self.catchBallDribble_7.setText(_translate("MainWindow", "Stop"))
        self.manualTab.setTabText(self.manualTab.indexOf(self.tab_5), _translate("MainWindow", "Go to coordinate"))
        self.robotStatusMonitor.setText(_translate("MainWindow", "Robot Status Monitor"))
        self.wheelMonitor.setText(_translate("MainWindow", "Wheel Monitor"))
        self.dribbleMonitor.setText(_translate("MainWindow", "Dribble Monitor"))
        self.positionMonitor.setText(_translate("MainWindow", "Position Monitor"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
