# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from rostu_interfaces/BallPositionBasedOnCamera.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class BallPositionBasedOnCamera(genpy.Message):
  _md5sum = "c32d588a00265202dbcab5311745340d"
  _type = "rostu_interfaces/BallPositionBasedOnCamera"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """int64 distance
int64 angle
int64 x_on_camera
int64 y_on_camera
int64 x_real
int64 y_real"""
  __slots__ = ['distance','angle','x_on_camera','y_on_camera','x_real','y_real']
  _slot_types = ['int64','int64','int64','int64','int64','int64']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       distance,angle,x_on_camera,y_on_camera,x_real,y_real

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(BallPositionBasedOnCamera, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.distance is None:
        self.distance = 0
      if self.angle is None:
        self.angle = 0
      if self.x_on_camera is None:
        self.x_on_camera = 0
      if self.y_on_camera is None:
        self.y_on_camera = 0
      if self.x_real is None:
        self.x_real = 0
      if self.y_real is None:
        self.y_real = 0
    else:
      self.distance = 0
      self.angle = 0
      self.x_on_camera = 0
      self.y_on_camera = 0
      self.x_real = 0
      self.y_real = 0

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_6q().pack(_x.distance, _x.angle, _x.x_on_camera, _x.y_on_camera, _x.x_real, _x.y_real))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 48
      (_x.distance, _x.angle, _x.x_on_camera, _x.y_on_camera, _x.x_real, _x.y_real,) = _get_struct_6q().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_6q().pack(_x.distance, _x.angle, _x.x_on_camera, _x.y_on_camera, _x.x_real, _x.y_real))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 48
      (_x.distance, _x.angle, _x.x_on_camera, _x.y_on_camera, _x.x_real, _x.y_real,) = _get_struct_6q().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_6q = None
def _get_struct_6q():
    global _struct_6q
    if _struct_6q is None:
        _struct_6q = struct.Struct("<6q")
    return _struct_6q
