// Generated by gencpp from file interfaces/Wheel.msg
// DO NOT EDIT!


#ifndef INTERFACES_MESSAGE_WHEEL_H
#define INTERFACES_MESSAGE_WHEEL_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace interfaces
{
template <class ContainerAllocator>
struct Wheel_
{
  typedef Wheel_<ContainerAllocator> Type;

  Wheel_()
    : halo()  {
    }
  Wheel_(const ContainerAllocator& _alloc)
    : halo(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _halo_type;
  _halo_type halo;





  typedef boost::shared_ptr< ::interfaces::Wheel_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::interfaces::Wheel_<ContainerAllocator> const> ConstPtr;

}; // struct Wheel_

typedef ::interfaces::Wheel_<std::allocator<void> > Wheel;

typedef boost::shared_ptr< ::interfaces::Wheel > WheelPtr;
typedef boost::shared_ptr< ::interfaces::Wheel const> WheelConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::interfaces::Wheel_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::interfaces::Wheel_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::interfaces::Wheel_<ContainerAllocator1> & lhs, const ::interfaces::Wheel_<ContainerAllocator2> & rhs)
{
  return lhs.halo == rhs.halo;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::interfaces::Wheel_<ContainerAllocator1> & lhs, const ::interfaces::Wheel_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace interfaces

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::interfaces::Wheel_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::interfaces::Wheel_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::interfaces::Wheel_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::interfaces::Wheel_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::interfaces::Wheel_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::interfaces::Wheel_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::interfaces::Wheel_<ContainerAllocator> >
{
  static const char* value()
  {
    return "1a3795d70ccd33e3facf9c5d221b1ac7";
  }

  static const char* value(const ::interfaces::Wheel_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x1a3795d70ccd33e3ULL;
  static const uint64_t static_value2 = 0xfacf9c5d221b1ac7ULL;
};

template<class ContainerAllocator>
struct DataType< ::interfaces::Wheel_<ContainerAllocator> >
{
  static const char* value()
  {
    return "interfaces/Wheel";
  }

  static const char* value(const ::interfaces::Wheel_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::interfaces::Wheel_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string halo\n"
;
  }

  static const char* value(const ::interfaces::Wheel_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::interfaces::Wheel_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.halo);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Wheel_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::interfaces::Wheel_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::interfaces::Wheel_<ContainerAllocator>& v)
  {
    s << indent << "halo: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.halo);
  }
};

} // namespace message_operations
} // namespace ros

#endif // INTERFACES_MESSAGE_WHEEL_H
