// Generated by gencpp from file rostu_interfaces/Dribble.msg
// DO NOT EDIT!


#ifndef ROSTU_INTERFACES_MESSAGE_DRIBBLE_H
#define ROSTU_INTERFACES_MESSAGE_DRIBBLE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace rostu_interfaces
{
template <class ContainerAllocator>
struct Dribble_
{
  typedef Dribble_<ContainerAllocator> Type;

  Dribble_()
    : left_motor(0.0)
    , right_motor(0.0)  {
    }
  Dribble_(const ContainerAllocator& _alloc)
    : left_motor(0.0)
    , right_motor(0.0)  {
  (void)_alloc;
    }



   typedef double _left_motor_type;
  _left_motor_type left_motor;

   typedef double _right_motor_type;
  _right_motor_type right_motor;





  typedef boost::shared_ptr< ::rostu_interfaces::Dribble_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rostu_interfaces::Dribble_<ContainerAllocator> const> ConstPtr;

}; // struct Dribble_

typedef ::rostu_interfaces::Dribble_<std::allocator<void> > Dribble;

typedef boost::shared_ptr< ::rostu_interfaces::Dribble > DribblePtr;
typedef boost::shared_ptr< ::rostu_interfaces::Dribble const> DribbleConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rostu_interfaces::Dribble_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rostu_interfaces::Dribble_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::rostu_interfaces::Dribble_<ContainerAllocator1> & lhs, const ::rostu_interfaces::Dribble_<ContainerAllocator2> & rhs)
{
  return lhs.left_motor == rhs.left_motor &&
    lhs.right_motor == rhs.right_motor;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::rostu_interfaces::Dribble_<ContainerAllocator1> & lhs, const ::rostu_interfaces::Dribble_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace rostu_interfaces

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::rostu_interfaces::Dribble_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rostu_interfaces::Dribble_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rostu_interfaces::Dribble_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rostu_interfaces::Dribble_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rostu_interfaces::Dribble_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rostu_interfaces::Dribble_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rostu_interfaces::Dribble_<ContainerAllocator> >
{
  static const char* value()
  {
    return "fbb6fd297edf2b990d3b5effd8454d72";
  }

  static const char* value(const ::rostu_interfaces::Dribble_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xfbb6fd297edf2b99ULL;
  static const uint64_t static_value2 = 0x0d3b5effd8454d72ULL;
};

template<class ContainerAllocator>
struct DataType< ::rostu_interfaces::Dribble_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rostu_interfaces/Dribble";
  }

  static const char* value(const ::rostu_interfaces::Dribble_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rostu_interfaces::Dribble_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 left_motor\n"
"float64 right_motor\n"
;
  }

  static const char* value(const ::rostu_interfaces::Dribble_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rostu_interfaces::Dribble_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.left_motor);
      stream.next(m.right_motor);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Dribble_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rostu_interfaces::Dribble_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::rostu_interfaces::Dribble_<ContainerAllocator>& v)
  {
    s << indent << "left_motor: ";
    Printer<double>::stream(s, indent + "  ", v.left_motor);
    s << indent << "right_motor: ";
    Printer<double>::stream(s, indent + "  ", v.right_motor);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROSTU_INTERFACES_MESSAGE_DRIBBLE_H
