// Generated by gencpp from file rostu_interfaces/KickerModule.msg
// DO NOT EDIT!


#ifndef ROSTU_INTERFACES_MESSAGE_KICKERMODULE_H
#define ROSTU_INTERFACES_MESSAGE_KICKERMODULE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace rostu_interfaces
{
template <class ContainerAllocator>
struct KickerModule_
{
  typedef KickerModule_<ContainerAllocator> Type;

  KickerModule_()
    : trigger(false)
    , charger(false)
    , status()  {
    }
  KickerModule_(const ContainerAllocator& _alloc)
    : trigger(false)
    , charger(false)
    , status(_alloc)  {
  (void)_alloc;
    }



   typedef uint8_t _trigger_type;
  _trigger_type trigger;

   typedef uint8_t _charger_type;
  _charger_type charger;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _status_type;
  _status_type status;





  typedef boost::shared_ptr< ::rostu_interfaces::KickerModule_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rostu_interfaces::KickerModule_<ContainerAllocator> const> ConstPtr;

}; // struct KickerModule_

typedef ::rostu_interfaces::KickerModule_<std::allocator<void> > KickerModule;

typedef boost::shared_ptr< ::rostu_interfaces::KickerModule > KickerModulePtr;
typedef boost::shared_ptr< ::rostu_interfaces::KickerModule const> KickerModuleConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rostu_interfaces::KickerModule_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rostu_interfaces::KickerModule_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::rostu_interfaces::KickerModule_<ContainerAllocator1> & lhs, const ::rostu_interfaces::KickerModule_<ContainerAllocator2> & rhs)
{
  return lhs.trigger == rhs.trigger &&
    lhs.charger == rhs.charger &&
    lhs.status == rhs.status;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::rostu_interfaces::KickerModule_<ContainerAllocator1> & lhs, const ::rostu_interfaces::KickerModule_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace rostu_interfaces

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::rostu_interfaces::KickerModule_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rostu_interfaces::KickerModule_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rostu_interfaces::KickerModule_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rostu_interfaces::KickerModule_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rostu_interfaces::KickerModule_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rostu_interfaces::KickerModule_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rostu_interfaces::KickerModule_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ba394d88a5c3e539dd36bff996be48d9";
  }

  static const char* value(const ::rostu_interfaces::KickerModule_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xba394d88a5c3e539ULL;
  static const uint64_t static_value2 = 0xdd36bff996be48d9ULL;
};

template<class ContainerAllocator>
struct DataType< ::rostu_interfaces::KickerModule_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rostu_interfaces/KickerModule";
  }

  static const char* value(const ::rostu_interfaces::KickerModule_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rostu_interfaces::KickerModule_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool trigger\n"
"bool charger\n"
"string status\n"
;
  }

  static const char* value(const ::rostu_interfaces::KickerModule_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rostu_interfaces::KickerModule_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.trigger);
      stream.next(m.charger);
      stream.next(m.status);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct KickerModule_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rostu_interfaces::KickerModule_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::rostu_interfaces::KickerModule_<ContainerAllocator>& v)
  {
    s << indent << "trigger: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.trigger);
    s << indent << "charger: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.charger);
    s << indent << "status: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.status);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROSTU_INTERFACES_MESSAGE_KICKERMODULE_H
