// Generated by gencpp from file rostu_interfaces/Wheel.msg
// DO NOT EDIT!


#ifndef ROSTU_INTERFACES_MESSAGE_WHEEL_H
#define ROSTU_INTERFACES_MESSAGE_WHEEL_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace rostu_interfaces
{
template <class ContainerAllocator>
struct Wheel_
{
  typedef Wheel_<ContainerAllocator> Type;

  Wheel_()
    : left_wheel(0.0)
    , right_wheel(0.0)
    , bottom_wheel(0.0)  {
    }
  Wheel_(const ContainerAllocator& _alloc)
    : left_wheel(0.0)
    , right_wheel(0.0)
    , bottom_wheel(0.0)  {
  (void)_alloc;
    }



   typedef double _left_wheel_type;
  _left_wheel_type left_wheel;

   typedef double _right_wheel_type;
  _right_wheel_type right_wheel;

   typedef double _bottom_wheel_type;
  _bottom_wheel_type bottom_wheel;





  typedef boost::shared_ptr< ::rostu_interfaces::Wheel_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rostu_interfaces::Wheel_<ContainerAllocator> const> ConstPtr;

}; // struct Wheel_

typedef ::rostu_interfaces::Wheel_<std::allocator<void> > Wheel;

typedef boost::shared_ptr< ::rostu_interfaces::Wheel > WheelPtr;
typedef boost::shared_ptr< ::rostu_interfaces::Wheel const> WheelConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rostu_interfaces::Wheel_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rostu_interfaces::Wheel_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::rostu_interfaces::Wheel_<ContainerAllocator1> & lhs, const ::rostu_interfaces::Wheel_<ContainerAllocator2> & rhs)
{
  return lhs.left_wheel == rhs.left_wheel &&
    lhs.right_wheel == rhs.right_wheel &&
    lhs.bottom_wheel == rhs.bottom_wheel;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::rostu_interfaces::Wheel_<ContainerAllocator1> & lhs, const ::rostu_interfaces::Wheel_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace rostu_interfaces

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::rostu_interfaces::Wheel_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rostu_interfaces::Wheel_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rostu_interfaces::Wheel_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rostu_interfaces::Wheel_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rostu_interfaces::Wheel_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rostu_interfaces::Wheel_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rostu_interfaces::Wheel_<ContainerAllocator> >
{
  static const char* value()
  {
    return "3043d084108e8cb8de33e26dbb60e64b";
  }

  static const char* value(const ::rostu_interfaces::Wheel_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x3043d084108e8cb8ULL;
  static const uint64_t static_value2 = 0xde33e26dbb60e64bULL;
};

template<class ContainerAllocator>
struct DataType< ::rostu_interfaces::Wheel_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rostu_interfaces/Wheel";
  }

  static const char* value(const ::rostu_interfaces::Wheel_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rostu_interfaces::Wheel_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 left_wheel\n"
"float64 right_wheel\n"
"float64 bottom_wheel\n"
;
  }

  static const char* value(const ::rostu_interfaces::Wheel_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rostu_interfaces::Wheel_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.left_wheel);
      stream.next(m.right_wheel);
      stream.next(m.bottom_wheel);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Wheel_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rostu_interfaces::Wheel_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::rostu_interfaces::Wheel_<ContainerAllocator>& v)
  {
    s << indent << "left_wheel: ";
    Printer<double>::stream(s, indent + "  ", v.left_wheel);
    s << indent << "right_wheel: ";
    Printer<double>::stream(s, indent + "  ", v.right_wheel);
    s << indent << "bottom_wheel: ";
    Printer<double>::stream(s, indent + "  ", v.bottom_wheel);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROSTU_INTERFACES_MESSAGE_WHEEL_H
