// Generated by gencpp from file rostu2024/DribbleSetting.msg
// DO NOT EDIT!


#ifndef ROSTU2024_MESSAGE_DRIBBLESETTING_H
#define ROSTU2024_MESSAGE_DRIBBLESETTING_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace rostu2024
{
template <class ContainerAllocator>
struct DribbleSetting_
{
  typedef DribbleSetting_<ContainerAllocator> Type;

  DribbleSetting_()
    : speed(0.0)
    , status()  {
    }
  DribbleSetting_(const ContainerAllocator& _alloc)
    : speed(0.0)
    , status(_alloc)  {
  (void)_alloc;
    }



   typedef double _speed_type;
  _speed_type speed;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _status_type;
  _status_type status;





  typedef boost::shared_ptr< ::rostu2024::DribbleSetting_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rostu2024::DribbleSetting_<ContainerAllocator> const> ConstPtr;

}; // struct DribbleSetting_

typedef ::rostu2024::DribbleSetting_<std::allocator<void> > DribbleSetting;

typedef boost::shared_ptr< ::rostu2024::DribbleSetting > DribbleSettingPtr;
typedef boost::shared_ptr< ::rostu2024::DribbleSetting const> DribbleSettingConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rostu2024::DribbleSetting_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rostu2024::DribbleSetting_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::rostu2024::DribbleSetting_<ContainerAllocator1> & lhs, const ::rostu2024::DribbleSetting_<ContainerAllocator2> & rhs)
{
  return lhs.speed == rhs.speed &&
    lhs.status == rhs.status;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::rostu2024::DribbleSetting_<ContainerAllocator1> & lhs, const ::rostu2024::DribbleSetting_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace rostu2024

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::rostu2024::DribbleSetting_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rostu2024::DribbleSetting_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rostu2024::DribbleSetting_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rostu2024::DribbleSetting_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rostu2024::DribbleSetting_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rostu2024::DribbleSetting_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rostu2024::DribbleSetting_<ContainerAllocator> >
{
  static const char* value()
  {
    return "18668401ab651fdaa2cebd8927c1fb8f";
  }

  static const char* value(const ::rostu2024::DribbleSetting_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x18668401ab651fdaULL;
  static const uint64_t static_value2 = 0xa2cebd8927c1fb8fULL;
};

template<class ContainerAllocator>
struct DataType< ::rostu2024::DribbleSetting_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rostu2024/DribbleSetting";
  }

  static const char* value(const ::rostu2024::DribbleSetting_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rostu2024::DribbleSetting_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 speed\n"
"string status\n"
;
  }

  static const char* value(const ::rostu2024::DribbleSetting_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rostu2024::DribbleSetting_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.speed);
      stream.next(m.status);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct DribbleSetting_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rostu2024::DribbleSetting_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::rostu2024::DribbleSetting_<ContainerAllocator>& v)
  {
    s << indent << "speed: ";
    Printer<double>::stream(s, indent + "  ", v.speed);
    s << indent << "status: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.status);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROSTU2024_MESSAGE_DRIBBLESETTING_H
