# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(1038, 754)
        MainWindow.setWindowTitle("Rostu Manual Monitor")
        MainWindow.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 491, 81))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label.setIndent(-1)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.speedSlider = QtWidgets.QSlider(self.verticalLayoutWidget)
        self.speedSlider.setMaximum(255)
        self.speedSlider.setTracking(True)
        self.speedSlider.setOrientation(QtCore.Qt.Horizontal)
        self.speedSlider.setObjectName("speedSlider")
        self.verticalLayout.addWidget(self.speedSlider)
        self.speedDisplay = QtWidgets.QSpinBox(self.verticalLayoutWidget)
        self.speedDisplay.setMaximum(255)
        self.speedDisplay.setObjectName("speedDisplay")
        self.verticalLayout.addWidget(self.speedDisplay)
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(10, 110, 251, 161))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.dialDirection = QtWidgets.QDial(self.verticalLayoutWidget_2)
        self.dialDirection.setMinimum(-270)
        self.dialDirection.setMaximum(90)
        self.dialDirection.setProperty("value", 90)
        self.dialDirection.setSliderPosition(90)
        self.dialDirection.setOrientation(QtCore.Qt.Vertical)
        self.dialDirection.setInvertedAppearance(True)
        self.dialDirection.setInvertedControls(False)
        self.dialDirection.setWrapping(True)
        self.dialDirection.setNotchTarget(0.0)
        self.dialDirection.setObjectName("dialDirection")
        self.verticalLayout_2.addWidget(self.dialDirection)
        self.directionDisplay = QtWidgets.QSpinBox(self.verticalLayoutWidget_2)
        self.directionDisplay.setMaximum(360)
        self.directionDisplay.setObjectName("directionDisplay")
        self.verticalLayout_2.addWidget(self.directionDisplay)
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(270, 110, 231, 161))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_3 = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_3.addWidget(self.label_3)
        self.dialRotation = QtWidgets.QDial(self.verticalLayoutWidget_3)
        self.dialRotation.setMouseTracking(False)
        self.dialRotation.setTabletTracking(False)
        self.dialRotation.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.dialRotation.setAcceptDrops(False)
        self.dialRotation.setToolTip("")
        self.dialRotation.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.dialRotation.setMinimum(-255)
        self.dialRotation.setMaximum(255)
        self.dialRotation.setPageStep(10)
        self.dialRotation.setProperty("value", 0)
        self.dialRotation.setSliderPosition(0)
        self.dialRotation.setTracking(True)
        self.dialRotation.setOrientation(QtCore.Qt.Horizontal)
        self.dialRotation.setInvertedAppearance(False)
        self.dialRotation.setInvertedControls(False)
        self.dialRotation.setNotchTarget(0.0)
        self.dialRotation.setNotchesVisible(False)
        self.dialRotation.setObjectName("dialRotation")
        self.verticalLayout_3.addWidget(self.dialRotation)
        self.rotationDisplay = QtWidgets.QSpinBox(self.verticalLayoutWidget_3)
        self.rotationDisplay.setMinimum(-255)
        self.rotationDisplay.setMaximum(255)
        self.rotationDisplay.setObjectName("rotationDisplay")
        self.verticalLayout_3.addWidget(self.rotationDisplay)
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(510, 10, 201, 121))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.runButton = QtWidgets.QPushButton(self.layoutWidget)
        self.runButton.setObjectName("runButton")
        self.verticalLayout_4.addWidget(self.runButton)
        self.stopButton = QtWidgets.QPushButton(self.layoutWidget)
        self.stopButton.setObjectName("stopButton")
        self.verticalLayout_4.addWidget(self.stopButton)
        self.statusLabel = QtWidgets.QLabel(self.layoutWidget)
        self.statusLabel.setObjectName("statusLabel")
        self.verticalLayout_4.addWidget(self.statusLabel)
        self.verticalLayoutWidget_4 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_4.setGeometry(QtCore.QRect(510, 140, 201, 131))
        self.verticalLayoutWidget_4.setObjectName("verticalLayoutWidget_4")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_4)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_6 = QtWidgets.QLabel(self.verticalLayoutWidget_4)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_6.addWidget(self.label_6)
        self.kickChargeTimeDisplay = QtWidgets.QSpinBox(self.verticalLayoutWidget_4)
        self.kickChargeTimeDisplay.setProperty("value", 3)
        self.kickChargeTimeDisplay.setObjectName("kickChargeTimeDisplay")
        self.verticalLayout_6.addWidget(self.kickChargeTimeDisplay)
        self.kickButton = QtWidgets.QPushButton(self.verticalLayoutWidget_4)
        self.kickButton.setObjectName("kickButton")
        self.verticalLayout_6.addWidget(self.kickButton)
        self.kickerStatusLabel = QtWidgets.QLabel(self.verticalLayoutWidget_4)
        self.kickerStatusLabel.setObjectName("kickerStatusLabel")
        self.verticalLayout_6.addWidget(self.kickerStatusLabel)
        self.verticalLayoutWidget_5 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_5.setGeometry(QtCore.QRect(720, 10, 201, 61))
        self.verticalLayoutWidget_5.setObjectName("verticalLayoutWidget_5")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_5)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_11 = QtWidgets.QLabel(self.verticalLayoutWidget_5)
        self.label_11.setObjectName("label_11")
        self.verticalLayout_5.addWidget(self.label_11)
        self.chaseBallButton = QtWidgets.QPushButton(self.verticalLayoutWidget_5)
        self.chaseBallButton.setObjectName("chaseBallButton")
        self.verticalLayout_5.addWidget(self.chaseBallButton)
        self.verticalLayoutWidget_6 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_6.setGeometry(QtCore.QRect(720, 80, 201, 106))
        self.verticalLayoutWidget_6.setObjectName("verticalLayoutWidget_6")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_6)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_12 = QtWidgets.QLabel(self.verticalLayoutWidget_6)
        self.label_12.setObjectName("label_12")
        self.verticalLayout_7.addWidget(self.label_12)
        self.catchBallDribble = QtWidgets.QRadioButton(self.verticalLayoutWidget_6)
        self.catchBallDribble.setObjectName("catchBallDribble")
        self.verticalLayout_7.addWidget(self.catchBallDribble)
        self.stopDribble = QtWidgets.QRadioButton(self.verticalLayoutWidget_6)
        self.stopDribble.setChecked(True)
        self.stopDribble.setObjectName("stopDribble")
        self.verticalLayout_7.addWidget(self.stopDribble)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_13 = QtWidgets.QLabel(self.verticalLayoutWidget_6)
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_5.addWidget(self.label_13)
        self.dribbleSpeed = QtWidgets.QSpinBox(self.verticalLayoutWidget_6)
        self.dribbleSpeed.setMaximum(255)
        self.dribbleSpeed.setObjectName("dribbleSpeed")
        self.horizontalLayout_5.addWidget(self.dribbleSpeed)
        self.verticalLayout_7.addLayout(self.horizontalLayout_5)
        self.verticalLayoutWidget_7 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_7.setGeometry(QtCore.QRect(270, 280, 231, 80))
        self.verticalLayoutWidget_7.setObjectName("verticalLayoutWidget_7")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_7)
        self.verticalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.label_8 = QtWidgets.QLabel(self.verticalLayoutWidget_7)
        self.label_8.setObjectName("label_8")
        self.verticalLayout_8.addWidget(self.label_8)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_9 = QtWidgets.QLabel(self.verticalLayoutWidget_7)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_6.addWidget(self.label_9)
        self.xPositionDisplay = QtWidgets.QLCDNumber(self.verticalLayoutWidget_7)
        self.xPositionDisplay.setObjectName("xPositionDisplay")
        self.horizontalLayout_6.addWidget(self.xPositionDisplay)
        self.label_10 = QtWidgets.QLabel(self.verticalLayoutWidget_7)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_6.addWidget(self.label_10)
        self.yPositionDisplay = QtWidgets.QLCDNumber(self.verticalLayoutWidget_7)
        self.yPositionDisplay.setObjectName("yPositionDisplay")
        self.horizontalLayout_6.addWidget(self.yPositionDisplay)
        self.verticalLayout_8.addLayout(self.horizontalLayout_6)
        self.verticalLayoutWidget_8 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_8.setGeometry(QtCore.QRect(10, 280, 251, 141))
        self.verticalLayoutWidget_8.setObjectName("verticalLayoutWidget_8")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_8)
        self.verticalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.label_4 = QtWidgets.QLabel(self.verticalLayoutWidget_8)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_10.addWidget(self.label_4)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_7 = QtWidgets.QLabel(self.verticalLayoutWidget_8)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_3.addWidget(self.label_7)
        self.bottomWheelDisplay = QtWidgets.QLCDNumber(self.verticalLayoutWidget_8)
        self.bottomWheelDisplay.setObjectName("bottomWheelDisplay")
        self.horizontalLayout_3.addWidget(self.bottomWheelDisplay)
        self.verticalLayout_10.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.left = QtWidgets.QLabel(self.verticalLayoutWidget_8)
        self.left.setObjectName("left")
        self.horizontalLayout_2.addWidget(self.left)
        self.leftWheelDisplay = QtWidgets.QLCDNumber(self.verticalLayoutWidget_8)
        self.leftWheelDisplay.setObjectName("leftWheelDisplay")
        self.horizontalLayout_2.addWidget(self.leftWheelDisplay)
        self.verticalLayout_10.addLayout(self.horizontalLayout_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_5 = QtWidgets.QLabel(self.verticalLayoutWidget_8)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout.addWidget(self.label_5)
        self.rightWheelDisplay = QtWidgets.QLCDNumber(self.verticalLayoutWidget_8)
        self.rightWheelDisplay.setObjectName("rightWheelDisplay")
        self.horizontalLayout.addWidget(self.rightWheelDisplay)
        self.verticalLayout_10.addLayout(self.horizontalLayout)
        self.verticalLayoutWidget_9 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_9.setGeometry(QtCore.QRect(10, 430, 251, 171))
        self.verticalLayoutWidget_9.setObjectName("verticalLayoutWidget_9")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_9)
        self.verticalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.label_14 = QtWidgets.QLabel(self.verticalLayoutWidget_9)
        self.label_14.setObjectName("label_14")
        self.verticalLayout_11.addWidget(self.label_14)
        self.compassDial = QtWidgets.QDial(self.verticalLayoutWidget_9)
        self.compassDial.setEnabled(False)
        self.compassDial.setAutoFillBackground(False)
        self.compassDial.setMinimum(-180)
        self.compassDial.setMaximum(180)
        self.compassDial.setOrientation(QtCore.Qt.Vertical)
        self.compassDial.setInvertedAppearance(False)
        self.compassDial.setInvertedControls(False)
        self.compassDial.setWrapping(True)
        self.compassDial.setObjectName("compassDial")
        self.verticalLayout_11.addWidget(self.compassDial)
        self.compassDisplay = QtWidgets.QLCDNumber(self.verticalLayoutWidget_9)
        self.compassDisplay.setObjectName("compassDisplay")
        self.verticalLayout_11.addWidget(self.compassDisplay)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        self.label.setText(_translate("MainWindow", "Speed (0 - 255)"))
        self.label_2.setText(_translate("MainWindow", "Direction (0 - 360)"))
        self.label_3.setText(_translate("MainWindow", "Rotation Speed (-255 - 255)"))
        self.runButton.setText(_translate("MainWindow", "Run"))
        self.stopButton.setText(_translate("MainWindow", "Stop"))
        self.statusLabel.setText(_translate("MainWindow", "Status : stop"))
        self.label_6.setText(_translate("MainWindow", "Set Charge Time (Second)"))
        self.kickButton.setText(_translate("MainWindow", "Kick"))
        self.kickerStatusLabel.setText(_translate("MainWindow", "Status : stop"))
        self.label_11.setText(_translate("MainWindow", "Action"))
        self.chaseBallButton.setText(_translate("MainWindow", "Chase Ball"))
        self.label_12.setText(_translate("MainWindow", "Dribble"))
        self.catchBallDribble.setText(_translate("MainWindow", "Catch Ball"))
        self.stopDribble.setText(_translate("MainWindow", "Stop"))
        self.label_13.setText(_translate("MainWindow", "Speed"))
        self.label_8.setText(_translate("MainWindow", "Position Monitor"))
        self.label_9.setText(_translate("MainWindow", "X"))
        self.label_10.setText(_translate("MainWindow", "Y"))
        self.label_4.setText(_translate("MainWindow", "Wheel speed monitor"))
        self.label_7.setText(_translate("MainWindow", "Bottom Wheel"))
        self.left.setText(_translate("MainWindow", "Left Wheel"))
        self.label_5.setText(_translate("MainWindow", "Right Wheel"))
        self.label_14.setText(_translate("MainWindow", "Compass monitor"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
