# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled2.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(1038, 754)
        MainWindow.setWindowTitle("Rostu Manual Monitor")
        MainWindow.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 451, 81))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label.setIndent(-1)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.speedSlider = QtWidgets.QSlider(self.verticalLayoutWidget)
        self.speedSlider.setMaximum(255)
        self.speedSlider.setTracking(True)
        self.speedSlider.setOrientation(QtCore.Qt.Horizontal)
        self.speedSlider.setObjectName("speedSlider")
        self.verticalLayout.addWidget(self.speedSlider)
        self.speedDisplay = QtWidgets.QSpinBox(self.verticalLayoutWidget)
        self.speedDisplay.setMaximum(255)
        self.speedDisplay.setObjectName("speedDisplay")
        self.verticalLayout.addWidget(self.speedDisplay)
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(470, 10, 201, 121))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.runButton = QtWidgets.QPushButton(self.layoutWidget)
        self.runButton.setObjectName("runButton")
        self.verticalLayout_4.addWidget(self.runButton)
        self.stopButton = QtWidgets.QPushButton(self.layoutWidget)
        self.stopButton.setObjectName("stopButton")
        self.verticalLayout_4.addWidget(self.stopButton)
        self.statusLabel = QtWidgets.QLabel(self.layoutWidget)
        self.statusLabel.setObjectName("statusLabel")
        self.verticalLayout_4.addWidget(self.statusLabel)
        self.verticalLayoutWidget_4 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_4.setGeometry(QtCore.QRect(470, 140, 201, 161))
        self.verticalLayoutWidget_4.setObjectName("verticalLayoutWidget_4")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_4)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_6 = QtWidgets.QLabel(self.verticalLayoutWidget_4)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_6.addWidget(self.label_6)
        self.kickChargeTimeDisplay = QtWidgets.QSpinBox(self.verticalLayoutWidget_4)
        self.kickChargeTimeDisplay.setProperty("value", 3)
        self.kickChargeTimeDisplay.setObjectName("kickChargeTimeDisplay")
        self.verticalLayout_6.addWidget(self.kickChargeTimeDisplay)
        self.kickButton = QtWidgets.QPushButton(self.verticalLayoutWidget_4)
        self.kickButton.setObjectName("kickButton")
        self.verticalLayout_6.addWidget(self.kickButton)
        self.kickerStatusLabel = QtWidgets.QLabel(self.verticalLayoutWidget_4)
        self.kickerStatusLabel.setObjectName("kickerStatusLabel")
        self.verticalLayout_6.addWidget(self.kickerStatusLabel)
        self.verticalLayoutWidget_5 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_5.setGeometry(QtCore.QRect(680, 10, 271, 161))
        self.verticalLayoutWidget_5.setObjectName("verticalLayoutWidget_5")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_5)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_11 = QtWidgets.QLabel(self.verticalLayoutWidget_5)
        self.label_11.setObjectName("label_11")
        self.verticalLayout_5.addWidget(self.label_11)
        self.chaseBallButton = QtWidgets.QPushButton(self.verticalLayoutWidget_5)
        self.chaseBallButton.setObjectName("chaseBallButton")
        self.verticalLayout_5.addWidget(self.chaseBallButton)
        self.label_18 = QtWidgets.QLabel(self.verticalLayoutWidget_5)
        self.label_18.setObjectName("label_18")
        self.verticalLayout_5.addWidget(self.label_18)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_19 = QtWidgets.QLabel(self.verticalLayoutWidget_5)
        self.label_19.setObjectName("label_19")
        self.horizontalLayout_4.addWidget(self.label_19)
        self.xGoToCoordinate = QtWidgets.QSpinBox(self.verticalLayoutWidget_5)
        self.xGoToCoordinate.setMaximum(1000)
        self.xGoToCoordinate.setObjectName("xGoToCoordinate")
        self.horizontalLayout_4.addWidget(self.xGoToCoordinate)
        self.label_20 = QtWidgets.QLabel(self.verticalLayoutWidget_5)
        self.label_20.setObjectName("label_20")
        self.horizontalLayout_4.addWidget(self.label_20)
        self.yGoToCoordinate = QtWidgets.QSpinBox(self.verticalLayoutWidget_5)
        self.yGoToCoordinate.setMaximum(1000)
        self.yGoToCoordinate.setObjectName("yGoToCoordinate")
        self.horizontalLayout_4.addWidget(self.yGoToCoordinate)
        self.verticalLayout_5.addLayout(self.horizontalLayout_4)
        self.buttonGoToCoordinate = QtWidgets.QPushButton(self.verticalLayoutWidget_5)
        self.buttonGoToCoordinate.setObjectName("buttonGoToCoordinate")
        self.verticalLayout_5.addWidget(self.buttonGoToCoordinate)
        self.verticalLayoutWidget_6 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_6.setGeometry(QtCore.QRect(680, 180, 271, 121))
        self.verticalLayoutWidget_6.setObjectName("verticalLayoutWidget_6")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_6)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_12 = QtWidgets.QLabel(self.verticalLayoutWidget_6)
        self.label_12.setObjectName("label_12")
        self.verticalLayout_7.addWidget(self.label_12)
        self.catchBallDribble = QtWidgets.QRadioButton(self.verticalLayoutWidget_6)
        self.catchBallDribble.setObjectName("catchBallDribble")
        self.verticalLayout_7.addWidget(self.catchBallDribble)
        self.stopDribble = QtWidgets.QRadioButton(self.verticalLayoutWidget_6)
        self.stopDribble.setChecked(True)
        self.stopDribble.setObjectName("stopDribble")
        self.verticalLayout_7.addWidget(self.stopDribble)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_13 = QtWidgets.QLabel(self.verticalLayoutWidget_6)
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_5.addWidget(self.label_13)
        self.dribbleSpeed = QtWidgets.QSpinBox(self.verticalLayoutWidget_6)
        self.dribbleSpeed.setMaximum(255)
        self.dribbleSpeed.setObjectName("dribbleSpeed")
        self.horizontalLayout_5.addWidget(self.dribbleSpeed)
        self.verticalLayout_7.addLayout(self.horizontalLayout_5)
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 100, 451, 201))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.dialDirection = QtWidgets.QDial(self.horizontalLayoutWidget)
        self.dialDirection.setMinimum(-270)
        self.dialDirection.setMaximum(90)
        self.dialDirection.setProperty("value", 90)
        self.dialDirection.setSliderPosition(90)
        self.dialDirection.setOrientation(QtCore.Qt.Vertical)
        self.dialDirection.setInvertedAppearance(True)
        self.dialDirection.setInvertedControls(False)
        self.dialDirection.setWrapping(True)
        self.dialDirection.setNotchTarget(0.0)
        self.dialDirection.setObjectName("dialDirection")
        self.verticalLayout_2.addWidget(self.dialDirection)
        self.directionDisplay = QtWidgets.QSpinBox(self.horizontalLayoutWidget)
        self.directionDisplay.setMaximum(360)
        self.directionDisplay.setObjectName("directionDisplay")
        self.verticalLayout_2.addWidget(self.directionDisplay)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_3 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_3.addWidget(self.label_3)
        self.dialRotation = QtWidgets.QDial(self.horizontalLayoutWidget)
        self.dialRotation.setMouseTracking(False)
        self.dialRotation.setTabletTracking(False)
        self.dialRotation.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.dialRotation.setAcceptDrops(False)
        self.dialRotation.setToolTip("")
        self.dialRotation.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.dialRotation.setMinimum(-255)
        self.dialRotation.setMaximum(255)
        self.dialRotation.setPageStep(10)
        self.dialRotation.setProperty("value", 0)
        self.dialRotation.setSliderPosition(0)
        self.dialRotation.setTracking(True)
        self.dialRotation.setOrientation(QtCore.Qt.Horizontal)
        self.dialRotation.setInvertedAppearance(False)
        self.dialRotation.setInvertedControls(False)
        self.dialRotation.setNotchTarget(0.0)
        self.dialRotation.setNotchesVisible(False)
        self.dialRotation.setObjectName("dialRotation")
        self.verticalLayout_3.addWidget(self.dialRotation)
        self.rotationDisplay = QtWidgets.QSpinBox(self.horizontalLayoutWidget)
        self.rotationDisplay.setMinimum(-255)
        self.rotationDisplay.setMaximum(255)
        self.rotationDisplay.setObjectName("rotationDisplay")
        self.verticalLayout_3.addWidget(self.rotationDisplay)
        self.horizontalLayout.addLayout(self.verticalLayout_3)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        self.label.setText(_translate("MainWindow", "Speed (0 - 255)"))
        self.runButton.setText(_translate("MainWindow", "Run"))
        self.stopButton.setText(_translate("MainWindow", "Stop"))
        self.statusLabel.setText(_translate("MainWindow", "Status : stop"))
        self.label_6.setText(_translate("MainWindow", "Set Charge Time (Second)"))
        self.kickButton.setText(_translate("MainWindow", "Kick"))
        self.kickerStatusLabel.setText(_translate("MainWindow", "Status : stop"))
        self.label_11.setText(_translate("MainWindow", "Action"))
        self.chaseBallButton.setText(_translate("MainWindow", "Chase Ball"))
        self.label_18.setText(_translate("MainWindow", "Go to coordinate"))
        self.label_19.setText(_translate("MainWindow", "x"))
        self.label_20.setText(_translate("MainWindow", "y"))
        self.buttonGoToCoordinate.setText(_translate("MainWindow", "Go"))
        self.label_12.setText(_translate("MainWindow", "Dribble"))
        self.catchBallDribble.setText(_translate("MainWindow", "Catch Ball"))
        self.stopDribble.setText(_translate("MainWindow", "Stop"))
        self.label_13.setText(_translate("MainWindow", "Speed"))
        self.label_2.setText(_translate("MainWindow", "Direction (0 - 360)"))
        self.label_3.setText(_translate("MainWindow", "Rotation Speed (-255 - 255)"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
