(cl:defpackage rostu_interfaces-msg
  (:use )
  (:export
   "<BALLPOSITIONBASEDONCAMERA>"
   "BALLPOSITIONBASEDONCAMERA"
   "<DRIBBLEMODULE>"
   "DRIBBLEMODULE"
   "<DRIBBLESETTING>"
   "DRIBBLESETTING"
   "<KICKERMODULE>"
   "KICKERMODULE"
   "<KICKERSETTING>"
   "KICKERSETTING"
   "<NAVIGATIONSETTING>"
   "NAVIGATIONSETTING"
   "<ROBOTSTATUS>"
   "ROBOTSTATUS"
   "<WHEEL>"
   "WHEEL"
  ))

